### DISCUSSION TITLE
HTTP Provider not evaluating the expected_status property

### DISCUSSION THREAD

**Discussion by ElijahSey** [chaostoolkit/chaostoolkit#313] [General]
In my experiment I want to terminate a kubernetes pod and test the api responses of the app right after.
In the generated journal I can see that the http request had a status of 500, which does not match the expected_status of 200:
```
"output": {
        "status": 500,
        "headers": {
          "Content-Type": "text/html;charset=UTF-8",
          "Content-Length": "6802",
          "Date": "Wed, 09 Apr 2025 18:52:43 GMT",
          "Connection": "close",
          "Server": "TeaStoreTomcat"
        },
        "body": "..."
      },
      "start": "2025-04-09T18:52:43.211760+00:00",
      "status": "succeeded",
      "end": "2025-04-09T18:52:43.321715+00:00",
      "duration": 0.109955
    },
    {
      "activity": {
        "type": "probe",
        "name": "browse_product",
        "provider": {
          "type": "http",
          "method": "POST",
          "url": "${url}/product?id=500",
          "expected_status": 200,
          "timeout": 5
        }
      },
```
Why is it, that the status of the probe is still "succeeded", although the output status does not match the expected_status?

Is there a way to get the probe to "fail" when the expected_status is not matched?

**Comment by cdsre** [comment]
Can you share the experiment.json ?

**Reply by ElijahSey** [reply]
Here is my whole experiment.yml.
The relevant part is the first few probes in the method.
```
title: Evaluate impact of killing pods
description: ...
configuration:
  url:
    type: env
    key: URL
    default: "http://192.168.99.2:30080/tools.descartes.teastore.webui/"
steady-state-hypothesis:
  title: Ensure that all deployments are ready
  probes:
    - type: probe
      name: db-fully-available
      tolerance: True
      provider:
        type: python
        module: chaosk8s.deployment.probes
        func: deployment_fully_available
        arguments:
          ns: teastore
          name: teastore-db
    - type: probe
      name: registry-fully-available
      tolerance: True
      provider:
        type: python
        module: chaosk8s.deployment.probes
        func: deployment_fully_available
        arguments:
          ns: teastore
          name: teastore-registry
    - type: probe
      name: persistence-fully-available
      tolerance: True
      provider:
        type: python
        module: chaosk8s.deployment.probes
        func: deployment_fully_available
        arguments:
          ns: teastore
          name: teastore-persistence
    - type: probe
      name: auth-fully-available
      tolerance: True
      provider:
        type: python
        module: chaosk8s.deployment.probes
        func: deployment_fully_available
        arguments:
          ns: teastore
          name: teastore-auth
    - type: probe
      name: recommender-fully-available
      tolerance: True
      provider:
        type: python
        module: chaosk8s.deployment.probes
        func: deployment_fully_available
        arguments:
          ns: teastore
          name: teastore-recommender
    - type: probe
      name: image-fully-available
      tolerance: True
      provider:
        type: python
        module: chaosk8s.deployment.probes
        func: deployment_fully_available
        arguments:
          ns: teastore
          name: teastore-image
    - type: probe
      name: webui-fully-available
      tolerance: True
      provider:
        type: python
        module: chaosk8s.deployment.probes
        func: deployment_fully_available
        arguments:
          ns: teastore
          name: teastore-webui
method:

  ### AUTH ###
  - type: action
    name: warmup-with-load
    pauses:
      after: 10
    provider:
      type: process
      path: locust
      arguments: "--config locust-warmup.conf"
  - type: action
    name: terminate-auth
    provider:
      type: python
      module: chaosk8s.pod.actions
      func: terminate_pods
      arguments:
        ns: teastore
        name_pattern: "teastore-auth-.*"
        grace_period: 0
  - type: probe
    name: visit-home
    provider:
      type: http
      method: GET
      url: "${url}"
      expected_status: 200
      timeout: 5
  - type: probe
    name: login
    provider:
      type: http
      method: POST
      url: "${url}/loginAction?username=1&password=password"
      expected_status: 200
      timeout: 5
  - type: probe
    name: browse-category
    provider:
      type: http
      method: GET
      url: "${url}/category?page=2&category=2"
      expected_status: 200
      timeout: 5
  - type: probe
    name: browse-product
    provider:
      type: http
      method: GET
      url: "${url}/product?id=500"
      expected_status: 200
      timeout: 5
  - type: probe
    name: add-product-to-cart
    provider:
      type: http
      method: POST
      url: "${url}/cartAction?productid=500"
      expected_status: 200
      timeout: 5
  - type: probe
    name: buy-products
    provider:
      type: http
      method: POST
      url: "${url}/cartAction?firstname=User&lastname=User&adress1=Road&adress2=City&cardtype=volvo&cardnumber=314159265359&expirydate=12/2050&confirm=Confirm"
      expected_status: 200
      timeout: 5
  - type: probe
    name: visit-profile
    provider:
      type: http
      method: GET
      url: "${url}/profile"
      expected_status: 200
      timeout: 5
  - type: probe
    name: logout
    provider:
      type: http
      method: POST
      url: "${url}/loginAction?logout="
      expected_status: 200
      timeout: 5
  - type: probe
    name: deployment-fully-available
    pauses:
      after: 30
    provider:
      type: python
      module: chaosk8s.deployment.probes
      func: deployment_fully_available
      arguments:
        ns: teastore
        name: teastore-auth
  
  ### RECOMMENDER ###
  - ref: warmup-with-load
  - type: action
    name: terminate-recommender
    provider:
      type: python
      module: chaosk8s.pod.actions
      func: terminate_pods
      arguments:
        ns: teastore
        name_pattern: "teastore-recommender-.*"
        grace_period: 0
  - ref: visit-home
  - ref: login
  - ref: browse-category
  - ref: browse-product
  - ref: add-product-to-cart
  - ref: buy-products
  - ref: visit-profile
  - ref: logout
  - type: probe
    name: deployment-fully-available
    pauses:
      after: 30
    provider:
      type: python
      module: chaosk8s.deployment.probes
      func: deployment_fully_available
      arguments:
        ns: teastore
        name: teastore-recommender

  ### IMAGE ###
  - ref: warmup-with-load
  - type: action
    name: terminate-image
    provider:
      type: python
      module: chaosk8s.pod.actions
      func: terminate_pods
      arguments:
        ns: teastore
        name_pattern: "teastore-image-.*"
        grace_period: 0
  - ref: visit-home
  - ref: login
  - ref: browse-category
  - ref: browse-product
  - ref: add-product-to-cart
  - ref: buy-products
  - ref: visit-profile
  - ref: logout
  - type: probe
    name: deployment-fully-available
    pauses:
      after: 30
    provider:
      type: python
      module: chaosk8s.deployment.probes
      func: deployment_fully_available
      arguments:
        ns: teastore
        name: teastore-image

  ### PERSISTENCE ###
  - ref: warmup-with-load
  - type: action
    name: terminate-persistence
    provider:
      type: python
      module: chaosk8s.pod.actions
      func: terminate_pods
      arguments:
        ns: teastore
        name_pattern: "teastore-persistence-.*"
        grace_period: 0
  - ref: visit-home
  - ref: login
  - ref: browse-category
  - ref: browse-product
  - ref: add-product-to-cart
  - ref: buy-products
  - ref: visit-profile
  - ref: logout
  - type: probe
    name: deployment-fully-available
    pauses:
      after: 30
    provider:
      type: python
      module: chaosk8s.deployment.probes
      func: deployment_fully_available
      arguments:
        ns: teastore
        name: teastore-persistence

  ### DB ###
  - ref: warmup-with-load
  - type: action
    name: terminate-db
    provider:
      type: python
      module: chaosk8s.pod.actions
      func: terminate_pods
      arguments:
        ns: teastore
        name_pattern: "teastore-db-.*"
        grace_period: 0
  - ref: visit-home
  - ref: login
  - ref: browse-category
  - ref: browse-product
  - ref: add-product-to-cart
  - ref: buy-products
  - ref: visit-profile
  - ref: logout
  - type: probe
    name: deployment-fully-available
    pauses:
      after: 30
    provider:
      type: python
      module: chaosk8s.deployment.probes
      func: deployment_fully_available
      arguments:
        ns: teastore
        name: teastore-db

  ### REGISTRY ###
  - ref: warmup-with-load
  - type: action
    name: terminate-registry
    provider:
      type: python
      module: chaosk8s.pod.actions
      func: terminate_pods
      arguments:
        ns: teastore
        name_pattern: "teastore-registry-.*"
        grace_period: 0
  - ref: visit-home
  - ref: login
  - ref: browse-category
  - ref: browse-product
  - ref: add-product-to-cart
  - ref: buy-products
  - ref: visit-profile
  - ref: logout
  - type: probe
    name: deployment-fully-available
    pauses:
      after: 30
    provider:
      type: python
      module: chaosk8s.deployment.probes
      func: deployment_fully_available
      arguments:
        ns: teastore
        name: teastore-registry
```
