### ISSUE TITLE
Allow configuration substitution on jsonpath expect

### ISSUE THREAD

**Issue by silvan02** [chaostoolkit/chaostoolkit#284]
**Is your feature request related to a problem? Please describe.**
```yaml
configuration:
  env:
    type: env
    key: ENV
    default: dev

steady-state-hypothesis:
  title: Check DNS Domains
  probes:
    - type: probe
      name: get-dns-cname
      provider:
        type: python
        module: chaosaws.route53.probes
        func: get_dns_answer
        arguments:
          zone_id: XXXX
          record_type: CNAME
          record_name: api.${env}.mysite.com
      tolerance:
        type: jsonpath
        path: $.RecordData[0]
        expect: my-other-cname.${env}.mysite.com
```

I need a test where the expected result could be configurable by a configuration as the example above.

**Describe the solution you'd like**
Allow to replace configurations on jsonpath expect as it was done for path on the release below
https://github.com/chaostoolkit/chaostoolkit-lib/compare/1.6.0...1.7.0

**Describe alternatives you've considered**
Cannot think on any alternative

**Additional context**
N/A
